package scraper

type ExchangePair struct {
	ID                int
	Pool              string
	Token1            string
	Token2            string
	Type              string
	Liquidity         float64
	LiquidityFormatted string
	APR               float64
	APRFormatted      string
	ExchangeID        string
}

func ScrapeZuitPairs() []ExchangePair {
	return []ExchangePair{
		{
			ID:                 1,
			Pool:               "ETH/ZRC",
			Token1:             "ETH",
			Token2:             "ZRC",
			Type:               "Base",
			Liquidity:          470016,
			LiquidityFormatted: "$470,016",
			APR:                2.8,
			APRFormatted:       "2.8%",
			ExchangeID:         "zuit",
		},
		{
			ID:                 2,
			Pool:               "USDC.e/USDT",
			Token1:             "USDC.e",
			Token2:             "USDT",
			Type:               "Stable",
			Liquidity:          194325,
			LiquidityFormatted: "$194,325",
			APR:                0.1,
			APRFormatted:       "0.1%",
			ExchangeID:         "zuit",
		},
		{
			ID:                 3,
			Pool:               "WBTC.e/ETH",
			Token1:             "WBTC.e",
			Token2:             "ETH",
			Type:               "Oasis",
			Liquidity:          100045,
			LiquidityFormatted: "$100,045",
			APR:                0.6,
			APRFormatted:       "0.6%",
			ExchangeID:         "zuit",
		},
		{
			ID:                 4,
			Pool:               "ETH/USDT",
			Token1:             "ETH",
			Token2:             "USDT",
			Type:               "Base",
			Liquidity:          9350,
			LiquidityFormatted: "$9,350",
			APR:                6.2,
			APRFormatted:       "6.2%",
			ExchangeID:         "zuit",
		},
		{
			ID:                 5,
			Pool:               "weETH/weETHs",
			Token1:             "weETH",
			Token2:             "weETHs",
			Type:               "Stable",
			Liquidity:          83689,
			LiquidityFormatted: "$83,689",
			APR:                4.0,
			APRFormatted:       "4%",
			ExchangeID:         "zuit",
		},
		{
			ID:                 6,
			Pool:               "ezETH/rsETH",
			Token1:             "ezETH",
			Token2:             "rsETH",
			Type:               "Stable",
			Liquidity:          47457,
			LiquidityFormatted: "$47,457",
			APR:                1.9,
			APRFormatted:       "1.9%",
			ExchangeID:         "zuit",
		},
		{
			ID:                 7,
			Pool:               "rsETH/weETHs",
			Token1:             "rsETH",
			Token2:             "weETHs",
			Type:               "Stable",
			Liquidity:          40256,
			LiquidityFormatted: "$40,256",
			APR:                6.9,
			APRFormatted:       "6.9%",
			ExchangeID:         "zuit",
		},
		{
			ID:                 8,
			Pool:               "weETH/rsETH",
			Token1:             "weETH",
			Token2:             "rsETH",
			Type:               "Stable",
			Liquidity:          23106,
			LiquidityFormatted: "$23,106",
			APR:                3.8,
			APRFormatted:       "3.8%",
			ExchangeID:         "zuit",
		},
		{
			ID:                 9,
			Pool:               "weETH/ETH",
			Token1:             "weETH",
			Token2:             "ETH",
			Type:               "Stable",
			Liquidity:          9742,
			LiquidityFormatted: "$9,742",
			APR:                11.1,
			APRFormatted:       "11.1%",
			ExchangeID:         "zuit",
		},
		{
			ID:                 10,
			Pool:               "WBTC.e/ETH",
			Token1:             "WBTC.e",
			Token2:             "ETH",
			Type:               "Base",
			Liquidity:          9393,
			LiquidityFormatted: "$9,393",
			APR:                4.0,
			APRFormatted:       "4%",
			ExchangeID:         "zuit",
		},
		{
			ID:                 11,
			Pool:               "ETH/weETHs",
			Token1:             "ETH",
			Token2:             "weETHs",
			Type:               "Stable",
			Liquidity:          9275,
			LiquidityFormatted: "$9,275",
			APR:                31.3,
			APRFormatted:       "31.3%",
			ExchangeID:         "zuit",
		},
		{
			ID:                 12,
			Pool:               "ETH/STONE",
			Token1:             "ETH",
			Token2:             "STONE",
			Type:               "Stable",
			Liquidity:          6632,
			LiquidityFormatted: "$6,632",
			APR:                94.7,
			APRFormatted:       "94.7%",
			ExchangeID:         "zuit",
		},
		{
			ID:                 13,
			Pool:               "rsETH/ETH",
			Token1:             "rsETH",
			Token2:             "ETH",
			Type:               "Stable",
			Liquidity:          5985,
			LiquidityFormatted: "$5,985",
			APR:                16.6,
			APRFormatted:       "16.6%",
			ExchangeID:         "zuit",
		},
		{
			ID:                 14,
			Pool:               "ETH/wetETH",
			Token1:             "ETH",
			Token2:             "wetETH",
			Type:               "Oasis",
			Liquidity:          1733,
			LiquidityFormatted: "$1,733",
			APR:                14.3,
			APRFormatted:       "14.3%",
			ExchangeID:         "zuit",
		},
		{
			ID:                 15,
			Pool:               "ETH/gmETH",
			Token1:             "ETH",
			Token2:             "gmETH",
			Type:               "Stable",
			Liquidity:          524,
			LiquidityFormatted: "$524",
			APR:                6.5,
			APRFormatted:       "6.5%",
			ExchangeID:         "zuit",
		},
	}
}
